# Generated by Django 2.2.6 on 2019-10-14 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
